# ref: https://github.com/linuxserver/docker-openssh-server/blob/master/Dockerfile.aarch64
# and modified allow tcp forwarding YES

#FROM ghcr.io/linuxserver/baseimage-alpine:arm64v8-3.18
FROM linuxserver/openssh-server:arm64v8-latest

RUN  sed -i 's/AllowTcpForwarding no/AllowTcpForwarding yes/g' /etc/ssh/sshd_config
